import type { Project, ProjectPrompt, ProjectDocument, ChecklistItem, ProjectMilestone } from "@/types";

export function buildFullProjectSpecMarkdown(
  project: Project,
  opts?: { prompts?: ProjectPrompt[]; docs?: ProjectDocument[]; checklist?: ChecklistItem[]; milestones?: ProjectMilestone[] }
): string {
  const lines: string[] = [];
  lines.push(`# ${project.title}`);
  lines.push(`**Stage:** ${project.stage} | **Priority:** ${project.priority} | **Progress:** ${project.percentComplete}%`);
  lines.push("");
  lines.push("## Overview");
  if (project.longDescription) lines.push(project.longDescription);
  else if (project.shortDescription) lines.push(project.shortDescription);
  lines.push("");
  if (project.targetAudience) { lines.push(`## Target Audience\n${project.targetAudience}\n`); }
  if (project.problemSolved) { lines.push(`## Problem Solved\n${project.problemSolved}\n`); }
  if (project.valueProposition) { lines.push(`## Value Proposition\n${project.valueProposition}\n`); }
  if (project.monetizationModel) { lines.push(`## Monetization\n${project.monetizationModel}\n`); }
  if (project.techStack?.length) { lines.push(`## Tech Stack\n${project.techStack.map(t => `- ${t}`).join("\n")}\n`); }
  lines.push("## Current Status");
  lines.push(`- **Stage:** ${project.stage}`);
  lines.push(`- **Priority:** ${project.priority}`);
  lines.push(`- **Progress:** ${project.percentComplete}%`);
  if (project.currentFocus) lines.push(`- **Current Focus:** ${project.currentFocus}`);
  if (project.nextAction) lines.push(`- **Next Action:** ${project.nextAction}`);
  if (project.blockers?.length) { lines.push(`\n## Blockers\n${project.blockers.map(b => `- ${b}`).join("\n")}`); }
  if (project.mvpDefinition) { lines.push(`\n## MVP Definition\n${project.mvpDefinition}`); }
  if (project.featureRoadmap) { lines.push(`\n## Feature Roadmap\n${project.featureRoadmap}`); }
  if (opts?.milestones?.length) {
    lines.push("\n## Milestones");
    opts.milestones.forEach(m => lines.push(`- [${m.status === "completed" ? "x" : " "}] ${m.title}`));
  }
  if (opts?.checklist?.length) {
    lines.push("\n## Launch Checklist");
    opts.checklist.forEach(c => lines.push(`- [${c.isComplete ? "x" : " "}] ${c.title}`));
  }
  if (opts?.prompts?.length) {
    lines.push("\n## Prompt Pack");
    opts.prompts.forEach(p => {
      lines.push(`\n### ${p.title} (${p.promptType})`);
      lines.push(p.body);
    });
  }
  lines.push(`\n---\n*Generated by FounderOS on ${new Date().toLocaleDateString()}*`);
  return lines.join("\n");
}

export function buildMvpSpecMarkdown(project: Project): string {
  const lines: string[] = [];
  lines.push(`# ${project.title} — MVP Spec`);
  lines.push("");
  if (project.mvpDefinition) lines.push(`## MVP Definition\n${project.mvpDefinition}\n`);
  if (project.techStack?.length) lines.push(`## Tech Stack\n${project.techStack.map(t => `- ${t}`).join("\n")}\n`);
  if (project.claudeBuildPrompt) lines.push(`## Claude Build Prompt\n${project.claudeBuildPrompt}\n`);
  if (project.featureRoadmap) lines.push(`## Feature Roadmap\n${project.featureRoadmap}\n`);
  lines.push(`---\n*Generated by FounderOS on ${new Date().toLocaleDateString()}*`);
  return lines.join("\n");
}

export function buildPromptPackMarkdown(project: Project, prompts: ProjectPrompt[]): string {
  const lines: string[] = [`# ${project.title} — Prompt Pack\n`];
  prompts.forEach(p => {
    lines.push(`## ${p.title}`);
    lines.push(`**Type:** ${p.promptType}`);
    if (p.intendedUse) lines.push(`**Use:** ${p.intendedUse}`);
    lines.push(`\n${p.body}\n`);
    lines.push("---");
  });
  return lines.join("\n");
}
